### ISSUE TITLE
this.request.getAccessToken is not a function

### ISSUE THREAD

**Issue by tony-gutierrez** [jovotech/jovo-framework-nodejs#126]
Trying to do: 
```
app.setHandler({
    'startRecircIntent': function () {
        const token = this.getAccessToken();
        this.tell('Start Recirc Intent!');
        
    }, ...
```

results in:
```
TypeError: this.request.getAccessToken is not a function
    at GoogleAction.getAccessToken (/Users/tony/rinnai_jovo/node_modules/jovo-framework/lib/platforms/googleaction/googleAction.js:120:29)
    at Jovo.getAccessToken (/Users/tony/rinnai_jovo/node_modules/jovo-framework/lib/jovo.js:272:35)
    at Jovo.startRecircIntent (/Users/tony/rinnai_jovo/lib/app.js:38:28)
    at Jovo.handleStatelessIntentRequest (/Users/tony/rinnai_jovo/node_modules/jovo-framework/lib/jovo.js:952:52)
    at Jovo.handleIntentRequest (/Users/tony/rinnai_jovo/node_modules/jovo-framework/lib/jovo.js:921:22)
    at loadUserDataOnRequest.then.then (/Users/tony/rinnai_jovo/node_modules/jovo-framework/lib/jovo.js:177:30)
    at <anonymous>
```

**Comment by jankoenig** [comment]
Hi @tony-gutierrez, which version of the Dialogflow API are you using? v1 or v2?

**Comment by tony-gutierrez** [comment]
v2

**Comment by jankoenig** [comment]
OK thanks. Will investigate together with @aswetlow
