### ISSUE TITLE
Unable to view Virtual output  design

### ISSUE THREAD

**Issue by deepakgd** [jovotech/jovo-framework-nodejs#157]
I followed this [tutorial](https://www.jovo.tech/framework/docs/google-assistant/visual-output) and [github](https://github.com/jovotech/jovo-framework-nodejs/blob/master/examples/google_action_specific/appGoogleAssistantCards.js#L44) code. Platform specific virtual output not working in google assistant. Please guide me how to fix this. Please review my code below

```
app.setHandler({
    'LAUNCH': function() {
        this.toIntent('HelloWorldIntent');
    },

    'HelloWorldIntent': function() {
        this.ask('Hello! What\'s your name?', 'Please tell me your name.');
    },

    'MyNameIsIntent': function(name) {
        let speech = 'Hey ' + name.value + ', nice to meet you! '+ 'Do you want to play game?';
        let reprompt = "Please answer with yes or no.";
        this.followUpState('OrderState').ask(speech, reprompt);
    },

    'OrderState': {
        'YesIntent' : function() {
            let type = this.getType();
            if(type == 'GoogleAction'){
               

             
               let basicCard = new BasicCard()
                .setTitle('Title')
                .setImage('http://via.placeholder.com/450x350?text=Basic+Card', 'accessibilityText')
                .setFormattedText('Formatted Text')
                .setImageDisplay('WHITE');

                this.googleAction().showBasicCard(basicCard);
                this.googleAction().showSuggestionChips(['List', 'Carousel', 'Basic card']);
                this.ask('Response with basic card', '?');

            }


           
        },

        'NoIntent' : function() {
           this.tell('Thank you for the time!');
        },
    },

    'AnswerIntent': function(){

    }
});
```

**Comment by deepakgd** [comment]
I got Connection timeout

**Comment by jankoenig** [comment]
Please paste the complete logs

**Comment by deepakgd** [comment]
Complete log:

Example server listening on port 3000!
This is your webhook url: https://webhook.jovo.cloud/a08fa5cf-5577-49e8-af1f-48d38fb978ef
```
{
	"responseId": "0eb77c4a-3eb3-4d97-9809-ac40f4c6da9a",
	"queryResult": {
		"queryText": "GOOGLE_ASSISTANT_WELCOME",
		"action": "input.welcome",
		"parameters": {},
		"allRequiredParamsPresent": true,
		"fulfillmentText": "Greetings!",
		"fulfillmentMessages": [
			{
				"text": {
					"text": [
						"Good day!"
					]
				}
			}
		],
		"outputContexts": [
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/google_assistant_welcome"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_screen_output"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_audio_output"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/google_assistant_input_type_keyboard"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_media_response_audio"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_web_browser"
			}
		],
		"intent": {
			"name": "projects/jovoquiz/agent/intents/856e88fe-47ad-41ea-8f85-0dd4ff6ee98e",
			"displayName": "Default Welcome Intent"
		},
		"intentDetectionConfidence": 1,
		"diagnosticInfo": {},
		"languageCode": "en-us"
	},
	"originalDetectIntentRequest": {
		"source": "google",
		"version": "2",
		"payload": {
			"isInSandbox": true,
			"surface": {
				"capabilities": [
					{
						"name": "actions.capability.WEB_BROWSER"
					},
					{
						"name": "actions.capability.AUDIO_OUTPUT"
					},
					{
						"name": "actions.capability.SCREEN_OUTPUT"
					},
					{
						"name": "actions.capability.MEDIA_RESPONSE_AUDIO"
					}
				]
			},
			"inputs": [
				{
					"rawInputs": [
						{
							"query": "Talk to my test app",
							"inputType": "KEYBOARD"
						}
					],
					"intent": "actions.intent.MAIN"
				}
			],
			"user": {
				"lastSeen": "2018-05-21T11:50:08Z",
				"locale": "en-US",
				"userId": "ABwppHFTErgCY7vwB18hpBp3vPP6vfMNKESZPwVAxoWzEf8cW3Y1bKqORWiDM-Nm7_pILD5y_cg"
			},
			"conversation": {
				"conversationId": "1526957505818",
				"type": "NEW"
			},
			"availableSurfaces": [
				{
					"capabilities": [
						{
							"name": "actions.capability.WEB_BROWSER"
						},
						{
							"name": "actions.capability.AUDIO_OUTPUT"
						},
						{
							"name": "actions.capability.SCREEN_OUTPUT"
						}
					]
				}
			]
		}
	},
	"session": "projects/jovoquiz/agent/sessions/1526957505818"
}
{
	"fulfillmentText": "<speak>Hello! What's your name?</speak>",
	"payload": {
		"google": {
			"expectUserResponse": true,
			"richResponse": {
				"items": [
					{
						"simpleResponse": {
							"ssml": "<speak>Hello! What's your name?</speak>"
						}
					}
				]
			},
			"noInputPrompts": [
				{
					"ssml": "<speak>Please tell me your name.</speak>"
				}
			]
		}
	},
	"outputContexts": [
		{
			"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/google_assistant_welcome"
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_screen_output"
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_audio_output"
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/google_assistant_input_type_keyboard"
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_media_response_audio"
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_web_browser"
		}
	]
}
{
	"responseId": "9514ee86-3d85-48b4-89bd-bfe9dfa6cf9b",
	"queryResult": {
		"queryText": "deepak",
		"parameters": {
			"name": "Deepak"
		},
		"allRequiredParamsPresent": true,
		"fulfillmentMessages": [
			{
				"text": {
					"text": [
						""
					]
				}
			}
		],
		"outputContexts": [
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_screen_output",
				"parameters": {
					"name.original": "deepak",
					"name": "Deepak"
				}
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_audio_output",
				"parameters": {
					"name.original": "deepak",
					"name": "Deepak"
				}
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/google_assistant_input_type_keyboard",
				"parameters": {
					"name.original": "deepak",
					"name": "Deepak"
				}
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_media_response_audio",
				"parameters": {
					"name.original": "deepak",
					"name": "Deepak"
				}
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_web_browser",
				"parameters": {
					"name.original": "deepak",
					"name": "Deepak"
				}
			}
		],
		"intent": {
			"name": "projects/jovoquiz/agent/intents/60daef21-4e53-4c27-aea6-86c0ae54d45a",
			"displayName": "MyNameIsIntent"
		},
		"intentDetectionConfidence": 0.83409387,
		"diagnosticInfo": {},
		"languageCode": "en-us"
	},
	"originalDetectIntentRequest": {
		"source": "google",
		"version": "2",
		"payload": {
			"isInSandbox": true,
			"surface": {
				"capabilities": [
					{
						"name": "actions.capability.SCREEN_OUTPUT"
					},
					{
						"name": "actions.capability.AUDIO_OUTPUT"
					},
					{
						"name": "actions.capability.WEB_BROWSER"
					},
					{
						"name": "actions.capability.MEDIA_RESPONSE_AUDIO"
					}
				]
			},
			"inputs": [
				{
					"rawInputs": [
						{
							"query": "deepak",
							"inputType": "KEYBOARD"
						}
					],
					"arguments": [
						{
							"rawText": "deepak",
							"textValue": "deepak",
							"name": "text"
						}
					],
					"intent": "actions.intent.TEXT"
				}
			],
			"user": {
				"lastSeen": "2018-05-21T11:50:08Z",
				"locale": "en-US",
				"userId": "ABwppHFTErgCY7vwB18hpBp3vPP6vfMNKESZPwVAxoWzEf8cW3Y1bKqORWiDM-Nm7_pILD5y_cg"
			},
			"conversation": {
				"conversationId": "1526957505818",
				"type": "ACTIVE",
				"conversationToken": "[]"
			},
			"availableSurfaces": [
				{
					"capabilities": [
						{
							"name": "actions.capability.SCREEN_OUTPUT"
						},
						{
							"name": "actions.capability.AUDIO_OUTPUT"
						},
						{
							"name": "actions.capability.WEB_BROWSER"
						}
					]
				}
			]
		}
	},
	"session": "projects/jovoquiz/agent/sessions/1526957505818"
}
{
	"fulfillmentText": "<speak>Hey Deepak, nice to meet you! Do you want to play game?</speak>",
	"payload": {
		"google": {
			"expectUserResponse": true,
			"richResponse": {
				"items": [
					{
						"simpleResponse": {
							"ssml": "<speak>Hey Deepak, nice to meet you! Do you want to play game?</speak>"
						}
					}
				]
			},
			"noInputPrompts": [
				{
					"ssml": "<speak>Please answer with yes or no.</speak>"
				}
			]
		}
	},
	"outputContexts": [
		{
			"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_screen_output",
			"parameters": {
				"name.original": "deepak",
				"name": "Deepak"
			}
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_audio_output",
			"parameters": {
				"name.original": "deepak",
				"name": "Deepak"
			}
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/google_assistant_input_type_keyboard",
			"parameters": {
				"name.original": "deepak",
				"name": "Deepak"
			}
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_media_response_audio",
			"parameters": {
				"name.original": "deepak",
				"name": "Deepak"
			}
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_web_browser",
			"parameters": {
				"name.original": "deepak",
				"name": "Deepak"
			}
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/session",
			"parameters": {
				"STATE": "OrderState"
			},
			"lifespanCount": 10000
		}
	]
}
{
	"responseId": "9f91b3d6-2188-42a7-85fa-fd2b44785312",
	"queryResult": {
		"queryText": "yes",
		"parameters": {},
		"allRequiredParamsPresent": true,
		"fulfillmentMessages": [
			{
				"text": {
					"text": [
						""
					]
				}
			}
		],
		"outputContexts": [
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_screen_output"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/session",
				"lifespanCount": 9999,
				"parameters": {
					"STATE": "OrderState"
				}
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_audio_output"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/google_assistant_input_type_keyboard"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_web_browser"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526957505818/contexts/actions_capability_media_response_audio"
			}
		],
		"intent": {
			"name": "projects/jovoquiz/agent/intents/4eb34eeb-3011-458d-8160-01f220b51c85",
			"displayName": "YesIntent"
		},
		"intentDetectionConfidence": 1,
		"diagnosticInfo": {},
		"languageCode": "en-us"
	},
	"originalDetectIntentRequest": {
		"source": "google",
		"version": "2",
		"payload": {
			"isInSandbox": true,
			"surface": {
				"capabilities": [
					{
						"name": "actions.capability.AUDIO_OUTPUT"
					},
					{
						"name": "actions.capability.SCREEN_OUTPUT"
					},
					{
						"name": "actions.capability.MEDIA_RESPONSE_AUDIO"
					},
					{
						"name": "actions.capability.WEB_BROWSER"
					}
				]
			},
			"inputs": [
				{
					"rawInputs": [
						{
							"query": "yes",
							"inputType": "KEYBOARD"
						}
					],
					"arguments": [
						{
							"rawText": "yes",
							"textValue": "yes",
							"name": "text"
						}
					],
					"intent": "actions.intent.TEXT"
				}
			],
			"user": {
				"lastSeen": "2018-05-21T11:50:08Z",
				"locale": "en-US",
				"userId": "ABwppHFTErgCY7vwB18hpBp3vPP6vfMNKESZPwVAxoWzEf8cW3Y1bKqORWiDM-Nm7_pILD5y_cg"
			},
			"conversation": {
				"conversationId": "1526957505818",
				"type": "ACTIVE",
				"conversationToken": "[\"session\"]"
			},
			"availableSurfaces": [
				{
					"capabilities": [
						{
							"name": "actions.capability.AUDIO_OUTPUT"
						},
						{
							"name": "actions.capability.SCREEN_OUTPUT"
						},
						{
							"name": "actions.capability.WEB_BROWSER"
						}
					]
				}
			]
		}
	},
	"session": "projects/jovoquiz/agent/sessions/1526957505818"
}

Timeout error: No response after 5000 milliseconds

{ Error: Timeout error: No response after 5000 milliseconds
    at createHangUpError (_http_client.js:336:15)
    at Socket.socketCloseListener (_http_client.js:368:23)
    at Socket.emit (events.js:185:15)
    at Socket.emit (domain.js:422:20)
    at TCP._handle.close [as _onclose] (net.js:541:12) code: 'ECONNRESET' }
```

**Comment by jankoenig** [comment]
It seems like it's not going into the `if` statement and doesn't have something to return then.
Two things:

1) Can you add an `else` statement with some output to test if that works?

2) Can you change `let type = this.getType(); if(type == 'GoogleAction')` to `if (this.isGoogleAction())` to see if that might be the problem?

**Comment by deepakgd** [comment]
I removed if condition but even after i am facing same issue, 

my complete code:

```
'use strict';

// =================================================================================
// App Configuration
// =================================================================================

const {App} = require('jovo-framework');
const {GoogleAction} = require('jovo-framework');
const BasicCard = GoogleAction.BasicCard
const questions = [
  {
    "question": "Who is Tottenham Hotspur's top goal scorer of all time?",
    "option1": "Jimmy Greaves",
    "option2": "Harry Kane",
    "option3": "Bobby Smith",
    "option4": "Cliff Jones",
    "category": "Spurs",
    "rightAnswer": "Jimmy Greaves",
  },
  {
    "question": "When was Tottenham Hotspur founded?",
    "option1": "1880",
    "option2": "1896",
    "option3": "1882",
    "option4": "1900",
    "category": "Spurs",
    "rightAnswer": "1882",
  },
  {
    "question": "What is the capacity of Tottenham Hotspur's new stadium?",
    "option1": "90000",
    "option2": "55000",
    "option3": "82000",
    "option4": "61000",
    "category": "Spurs",
    "rightAnswer": "61000",
  },
  {
    "question": "In which city did Spurs last win a trophy?",
    "option1": "London",
    "option2": "Berlin",
    "option3": "Dublin",
    "option4": "Madrid",
    "category": "Spurs",
    "rightAnswer": "London",
  },
  {
    "question": "What is Tottenham Hotspur's emblem?",
    "option1": "Cockerel",
    "option2": "Lion",
    "option3": "Swan",
    "option4": "Rose",
    "category": "Spurs",
    "rightAnswer": "Cockerel",
  }
];

const config = {
    logging: true,
};

const app = new App(config);

// =================================================================================
// App Logic
// =================================================================================

app.setHandler({
    'LAUNCH': function() {
        this.toIntent('HelloWorldIntent');
    },

    'HelloWorldIntent': function() {
        this.ask('Hello! What\'s your name?', 'Please tell me your name.');
    },

    'MyNameIsIntent': function(name) {
        let speech = 'Hey ' + name.value + ', nice to meet you! '+ 'Do you want to play game?';
        let reprompt = "Please answer with yes or no.";
        this.followUpState('OrderState').ask(speech, reprompt);
    },

    'OrderState': {
        'YesIntent' : function() {
            let type = this.getType();
                let question = questions[Math.floor(Math.random() * (4 - 0 + 1)) + 0];

             
               let basicCard = new GoogleAction.BasicCard()
            .setTitle('Title')
            .setImage('http://via.placeholder.com/450x350?text=Basic+Card', 'accessibilityText')
            .setFormattedText('Formatted Text')
            .setImageDisplay('WHITE');

        this.googleAction().showBasicCard(basicCard);
        this.googleAction().showSuggestionChips(['List', 'Carousel', 'Basic card']);
        this.ask('Response with basic card', '?');



           
        },

        'NoIntent' : function() {
           this.tell('Thank you for the time!');
        },
    },

    'AnswerIntent': function(){

    }
});

module.exports.app = app;
```


log:

```
Example server listening on port 3000!
This is your webhook url: https://webhook.jovo.cloud/a08fa5cf-5577-49e8-af1f-48d38fb978ef
{
	"responseId": "3a0c4777-13bd-4b50-95d1-b8129f4af7dc",
	"queryResult": {
		"queryText": "GOOGLE_ASSISTANT_WELCOME",
		"action": "input.welcome",
		"parameters": {},
		"allRequiredParamsPresent": true,
		"fulfillmentText": "Greetings!",
		"fulfillmentMessages": [
			{
				"text": {
					"text": [
						"Greetings!"
					]
				}
			}
		],
		"outputContexts": [
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/google_assistant_welcome"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_screen_output"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_audio_output"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/google_assistant_input_type_keyboard"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_web_browser"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_media_response_audio"
			}
		],
		"intent": {
			"name": "projects/jovoquiz/agent/intents/856e88fe-47ad-41ea-8f85-0dd4ff6ee98e",
			"displayName": "Default Welcome Intent"
		},
		"intentDetectionConfidence": 1,
		"diagnosticInfo": {},
		"languageCode": "en-us"
	},
	"originalDetectIntentRequest": {
		"source": "google",
		"version": "2",
		"payload": {
			"isInSandbox": true,
			"surface": {
				"capabilities": [
					{
						"name": "actions.capability.WEB_BROWSER"
					},
					{
						"name": "actions.capability.MEDIA_RESPONSE_AUDIO"
					},
					{
						"name": "actions.capability.SCREEN_OUTPUT"
					},
					{
						"name": "actions.capability.AUDIO_OUTPUT"
					}
				]
			},
			"inputs": [
				{
					"rawInputs": [
						{
							"query": "Talk to jovo test app",
							"inputType": "KEYBOARD"
						}
					],
					"intent": "actions.intent.MAIN"
				}
			],
			"user": {
				"lastSeen": "2018-05-22T06:51:07Z",
				"locale": "en-US",
				"userId": "ABwppHFTErgCY7vwB18hpBp3vPP6vfMNKESZPwVAxoWzEf8cW3Y1bKqORWiDM-Nm7_pILD5y_cg"
			},
			"conversation": {
				"conversationId": "1526985873852",
				"type": "NEW"
			},
			"availableSurfaces": [
				{
					"capabilities": [
						{
							"name": "actions.capability.WEB_BROWSER"
						},
						{
							"name": "actions.capability.SCREEN_OUTPUT"
						},
						{
							"name": "actions.capability.AUDIO_OUTPUT"
						}
					]
				}
			]
		}
	},
	"session": "projects/jovoquiz/agent/sessions/1526985873852"
}
{
	"fulfillmentText": "<speak>Hello! What's your name?</speak>",
	"payload": {
		"google": {
			"expectUserResponse": true,
			"richResponse": {
				"items": [
					{
						"simpleResponse": {
							"ssml": "<speak>Hello! What's your name?</speak>"
						}
					}
				]
			},
			"noInputPrompts": [
				{
					"ssml": "<speak>Please tell me your name.</speak>"
				}
			]
		}
	},
	"outputContexts": [
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/google_assistant_welcome"
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_screen_output"
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_audio_output"
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/google_assistant_input_type_keyboard"
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_web_browser"
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_media_response_audio"
		}
	]
}
{
	"responseId": "6f951a23-16d3-4f41-9d9c-03a25da041e4",
	"queryResult": {
		"queryText": "deepak",
		"parameters": {
			"name": "Deepak"
		},
		"allRequiredParamsPresent": true,
		"fulfillmentMessages": [
			{
				"text": {
					"text": [
						""
					]
				}
			}
		],
		"outputContexts": [
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_screen_output",
				"parameters": {
					"name.original": "deepak",
					"name": "Deepak"
				}
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_audio_output",
				"parameters": {
					"name.original": "deepak",
					"name": "Deepak"
				}
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/google_assistant_input_type_keyboard",
				"parameters": {
					"name.original": "deepak",
					"name": "Deepak"
				}
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_web_browser",
				"parameters": {
					"name.original": "deepak",
					"name": "Deepak"
				}
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_media_response_audio",
				"parameters": {
					"name.original": "deepak",
					"name": "Deepak"
				}
			}
		],
		"intent": {
			"name": "projects/jovoquiz/agent/intents/60daef21-4e53-4c27-aea6-86c0ae54d45a",
			"displayName": "MyNameIsIntent"
		},
		"intentDetectionConfidence": 0.83409387,
		"diagnosticInfo": {},
		"languageCode": "en-us"
	},
	"originalDetectIntentRequest": {
		"source": "google",
		"version": "2",
		"payload": {
			"isInSandbox": true,
			"surface": {
				"capabilities": [
					{
						"name": "actions.capability.MEDIA_RESPONSE_AUDIO"
					},
					{
						"name": "actions.capability.WEB_BROWSER"
					},
					{
						"name": "actions.capability.AUDIO_OUTPUT"
					},
					{
						"name": "actions.capability.SCREEN_OUTPUT"
					}
				]
			},
			"inputs": [
				{
					"rawInputs": [
						{
							"query": "deepak",
							"inputType": "KEYBOARD"
						}
					],
					"arguments": [
						{
							"rawText": "deepak",
							"textValue": "deepak",
							"name": "text"
						}
					],
					"intent": "actions.intent.TEXT"
				}
			],
			"user": {
				"lastSeen": "2018-05-22T06:51:07Z",
				"locale": "en-US",
				"userId": "ABwppHFTErgCY7vwB18hpBp3vPP6vfMNKESZPwVAxoWzEf8cW3Y1bKqORWiDM-Nm7_pILD5y_cg"
			},
			"conversation": {
				"conversationId": "1526985873852",
				"type": "ACTIVE",
				"conversationToken": "[]"
			},
			"availableSurfaces": [
				{
					"capabilities": [
						{
							"name": "actions.capability.WEB_BROWSER"
						},
						{
							"name": "actions.capability.AUDIO_OUTPUT"
						},
						{
							"name": "actions.capability.SCREEN_OUTPUT"
						}
					]
				}
			]
		}
	},
	"session": "projects/jovoquiz/agent/sessions/1526985873852"
}
{
	"fulfillmentText": "<speak>Hey Deepak, nice to meet you! Do you want to play game?</speak>",
	"payload": {
		"google": {
			"expectUserResponse": true,
			"richResponse": {
				"items": [
					{
						"simpleResponse": {
							"ssml": "<speak>Hey Deepak, nice to meet you! Do you want to play game?</speak>"
						}
					}
				]
			},
			"noInputPrompts": [
				{
					"ssml": "<speak>Please answer with yes or no.</speak>"
				}
			]
		}
	},
	"outputContexts": [
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_screen_output",
			"parameters": {
				"name.original": "deepak",
				"name": "Deepak"
			}
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_audio_output",
			"parameters": {
				"name.original": "deepak",
				"name": "Deepak"
			}
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/google_assistant_input_type_keyboard",
			"parameters": {
				"name.original": "deepak",
				"name": "Deepak"
			}
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_web_browser",
			"parameters": {
				"name.original": "deepak",
				"name": "Deepak"
			}
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_media_response_audio",
			"parameters": {
				"name.original": "deepak",
				"name": "Deepak"
			}
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/session",
			"parameters": {
				"STATE": "OrderState"
			},
			"lifespanCount": 10000
		}
	]
}
{
	"responseId": "023a4bde-0edf-4dd8-8f97-1871c6aeb682",
	"queryResult": {
		"queryText": "yes",
		"parameters": {},
		"allRequiredParamsPresent": true,
		"fulfillmentMessages": [
			{
				"text": {
					"text": [
						""
					]
				}
			}
		],
		"outputContexts": [
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/session",
				"lifespanCount": 9999,
				"parameters": {
					"STATE": "OrderState"
				}
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_screen_output"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_audio_output"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/google_assistant_input_type_keyboard"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_web_browser"
			},
			{
				"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_media_response_audio"
			}
		],
		"intent": {
			"name": "projects/jovoquiz/agent/intents/4eb34eeb-3011-458d-8160-01f220b51c85",
			"displayName": "YesIntent"
		},
		"intentDetectionConfidence": 1,
		"diagnosticInfo": {},
		"languageCode": "en-us"
	},
	"originalDetectIntentRequest": {
		"source": "google",
		"version": "2",
		"payload": {
			"isInSandbox": true,
			"surface": {
				"capabilities": [
					{
						"name": "actions.capability.AUDIO_OUTPUT"
					},
					{
						"name": "actions.capability.SCREEN_OUTPUT"
					},
					{
						"name": "actions.capability.MEDIA_RESPONSE_AUDIO"
					},
					{
						"name": "actions.capability.WEB_BROWSER"
					}
				]
			},
			"inputs": [
				{
					"rawInputs": [
						{
							"query": "yes",
							"inputType": "KEYBOARD"
						}
					],
					"arguments": [
						{
							"rawText": "yes",
							"textValue": "yes",
							"name": "text"
						}
					],
					"intent": "actions.intent.TEXT"
				}
			],
			"user": {
				"lastSeen": "2018-05-22T06:51:07Z",
				"locale": "en-US",
				"userId": "ABwppHFTErgCY7vwB18hpBp3vPP6vfMNKESZPwVAxoWzEf8cW3Y1bKqORWiDM-Nm7_pILD5y_cg"
			},
			"conversation": {
				"conversationId": "1526985873852",
				"type": "ACTIVE",
				"conversationToken": "[\"session\"]"
			},
			"availableSurfaces": [
				{
					"capabilities": [
						{
							"name": "actions.capability.AUDIO_OUTPUT"
						},
						{
							"name": "actions.capability.SCREEN_OUTPUT"
						},
						{
							"name": "actions.capability.WEB_BROWSER"
						}
					]
				}
			]
		}
	},
	"session": "projects/jovoquiz/agent/sessions/1526985873852"
}
{
	"fulfillmentText": "<speak>Response with basic card</speak>",
	"payload": {
		"google": {
			"expectUserResponse": true,
			"richResponse": {
				"items": [
					{
						"simpleResponse": {
							"ssml": "<speak>Response with basic card</speak>"
						}
					},
					{
						"basicCard": {
							"title": "Title",
							"image": {
								"url": "http://via.placeholder.com/450x350?text=Basic+Card",
								"accessibilityText": "accessibilityText"
							},
							"formattedText": "Formatted Text",
							"imageDisplayOptions": "WHITE"
						}
					}
				],
				"suggestions": [
					{
						"title": "List"
					},
					{
						"title": "Carousel"
					},
					{
						"title": "Basic card"
					}
				]
			},
			"noInputPrompts": [
				{
					"ssml": "<speak>?</speak>"
				}
			]
		}
	},
	"outputContexts": [
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/session",
			"lifespanCount": 9999,
			"parameters": {
				"STATE": "OrderState"
			}
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_screen_output"
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_audio_output"
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/google_assistant_input_type_keyboard"
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_web_browser"
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/actions_capability_media_response_audio"
		},
		{
			"name": "projects/jovoquiz/agent/sessions/1526985873852/contexts/session",
			"parameters": {
				"STATE": "OrderState"
			},
			"lifespanCount": 10000
		}
	]
}

```
[output image
](https://drive.google.com/file/d/1tJhzmP8sfR1Ioxuiv5ZpS5o6jrbnSOgc/view?usp=sharing)

**Comment by deepakgd** [comment]
it would be great if you share working code or example

**Comment by jankoenig** [comment]
Hm, the card is in the response

```
"richResponse": {
				"items": [
					{
						"simpleResponse": {
							"ssml": "<speak>Response with basic card</speak>"
						}
					},
					{
						"basicCard": {
							"title": "Title",
							"image": {
								"url": "http://via.placeholder.com/450x350?text=Basic+Card",
								"accessibilityText": "accessibilityText"
							},
							"formattedText": "Formatted Text",
							"imageDisplayOptions": "WHITE"
						}
					}
				],
```

Have you selected "Phone" or "Speaker" as surface (to the upper right of the simulator)?

**Comment by deepakgd** [comment]
yes i got it. card response  is available in right side panel display tab. Thanks for your support.
