### ISSUE TITLE
Jovo get won't work when title has apostrophe

### ISSUE THREAD

**Issue by QuentinDela** [jovotech/jovo-framework-nodejs#159]
- [X ] Bug report

## Expected Behavior

When using "jovo get", it should update the Alexa data in the local model.

## Current Behavior
```
 SyntaxError: /Users/Royal/dev/dialog/sons/sonsAmbiance/platforms/alexaSkill/skill.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:679:27)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.getSkillJson (/usr/local/lib/node_modules/jovo-cli/helper/alexaUtil.js:121:20)
    at Object.getSkillSimpleInformation (/usr/local/lib/node_modules/jovo-cli/helper/alexaUtil.js:404:30)
    at p.then.then.then.then.then.then (/usr/local/lib/node_modules/jovo-cli/commands/tasks.js:103:57)
```

## Your Environment
* Jovo Framework version used: 1.0.17

**Comment by jankoenig** [comment]
Hi @QuentinDela, could you share that part of the skill.json? (private message in our Slack is also OK if you don't want to publicly share it)

**Comment by QuentinDela** [comment]
It seems to be working finally. Sorry :).
