### ISSUE TITLE
Error: 'userData' as NULL when using DynamoDB config

### ISSUE THREAD

**Issue by availit** [jovotech/jovo-framework-nodejs#161]
## I'm submitting a...
- [X] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
DynamoDB connection to update table with userData

## Current Behavior
I receive the error log on the launch request of my Alexa app. It throws again on the request timeout.
The local DB file works for testing.

When including the database object in config settings of _app.js_ the error pops up when calling a launch request
```
db: {
        type: 'dynamodb',
        tableName: 'NewTable'
    }
```

### Error log
```
TypeError: Cannot read property 'userData' of null
    at platform.jovo.db.loadObject (C:\~\node_modules\jovo-framework\lib\user.js:39:33)
    at DynamoDb.checkResourceNotFound (C:\~\node_modules\jovo-framework\lib\integrations\db\dynamoDb.js:328:13)
    at Response.<anonymous> (C:\~\node_modules\jovo-framework\lib\integrations\db\dynamoDb.js:209:22)
```

## Your Environment

* Jovo Framework version used: 1.2.0
* Operating System: Windows 10
* Deployed to AWS Lambda

**Comment by jankoenig** [comment]
Hi @availit. Thanks, we're taking a look at this

**Comment by aswetlow** [comment]
Hey @availit !
How did you create your table?

Could you please log the error after line 34 in  /node_modules/jovo-framework/lib/user.js 

```javascript
...
this.platform.jovo.db().loadObject((error, data) => {
console.log(error);
...
```

**Comment by availit** [comment]
Hi @aswetlow!
I was trying to create my table by giving it a name in the config and having jovo create it for me, at least that's what @jankoenig had mentioned to me is possible. The local DB file works great btw..

Here is the error I got to log after making a launch request:

```
ConfigError: Missing region in config
    at Request.VALIDATE_REGION (C:\Users\~\node_modules\aws-sdk\lib\event_listeners.js:91:45)
    at Request.callListeners (C:\Users\~\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at callNextListener (C:\Users\~\node_modules\aws-sdk\lib\sequential_executor.js:95:12)
    at C:\Users\~\node_modules\aws-sdk\lib\event_listeners.js:85:9
    at finish (C:\Users\~\node_modules\aws-sdk\lib\config.js:320:7)
    at C:\Users\~\node_modules\aws-sdk\lib\config.js:338:9
    at SharedIniFileCredentials.get (C:\Users\~\node_modules\aws-sdk\lib\credentials.js:126:7)
    at getAsyncCredentials (C:\Users\~\node_modules\aws-sdk\lib\config.js:332:24)
    at Config.getCredentials (C:\Users\~\node_modules\aws-sdk\lib\config.js:352:9)
    at Request.VALIDATE_CREDENTIALS (C:\Users\~\node_modules\aws-sdk\lib\event_listeners.js:80:26)
  message: 'Missing region in config',
  code: 'ConfigError',
  time: 2018-05-29T15:35:40.998Z
```

**Comment by jankoenig** [comment]
Hi @availit, are you sure you're running it on Lambda? The paths (`C:\Users\~\node_modules\aws-sdk\lib\event_listeners.js:91:45`)  indicate that you're running it on your computer.

If you're running it on your computer, you need to add the AWS credentials, like this:
```
let awsConfig = {
    accessKeyId: 'yourAccessKeyId',
    secretAccessKey: 'yourSecretAccessKey', 
    region:  'yourRegion',
};

// Using the constructor
const config = {
    db: {
        type: 'dynamodb',
        tableName: 'TableName',
        awsConfig: awsConfig,
    },
    // Other configurations
};
```
Take a look here https://www.jovo.tech/framework/docs/databases#dynamodb-for-apps-not-hosted-on-aws-lambda

**Comment by availit** [comment]
Okay I just tested it on AWS and it's not creating a table.
No matter what I ask or say to my skill it just hits the Unhandled function until I comment out the DB config in the app.js file.
I can't find the log inside AWS for the user.js @aswetlow mentioned earlier? Sorry I'm a noob at aws lambda

**Comment by jankoenig** [comment]
You can find them in Cloudwatch https://console.aws.amazon.com/cloudwatch

**Comment by availit** [comment]
Another interesting thing, I thought it was going to Unhandled but it just goes to the LAUNCH intent no matter what I say.. 

**The Request:**
```
{
    "type": "IntentRequest",
    "requestId": "amzn1.echo-api.request.e6517939-caa8-42c4-be83-920a14326244",
    "timestamp": "2018-05-29T16:50:42Z",
    "locale": "en-US",
    "intent": {
        "name": "SelectLocationIntent",
        "confirmationStatus": "NONE",
        "slots": {
            "store": {
                "name": "store",
                "value": "pla",
                "resolutions": {
                    "resolutionsPerAuthority": [
                        {
                            "authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.cda18187-d800-4c43-b382-c080898dba79.centerCode",
                            "status": {
                                "code": "ER_SUCCESS_MATCH"
                            },
                            "values": [
                                {
                                    "value": {
                                        "name": "PLA",
                                        "id": "a9ae8dcc04ef529de1153d5731c4d65c"
                                    }
                                }
                            ]
                        }
                    ]
                },
                "confirmationStatus": "NONE"
            }
        }
    },
    "dialogState": "STARTED"
}
```

**The Response:**
```
2018-05-29T16:50:42.258Z	6c64ddc7-6360-11e8-bb62-0980c87d606c
{
    "version": "1.0",
    "response": {
        "shouldEndSession": false,
        "outputSpeech": {
            "type": "SSML",
            "ssml": "<speak>hello! welcome! what would you like to do?</speak>"
        },
        "reprompt": {
            "outputSpeech": {
                "type": "SSML",
                "ssml": "<speak>please say a command.</speak>"
            }
        }
    },
    "sessionAttributes": {}
}
```

**Comment by jankoenig** [comment]
We added some additional info here: https://www.jovo.tech/guides/add-dynamodb-database Let us know if your issue "persists" (pun intended)
