### ISSUE TITLE
Displaying Standard Card Throws Error

### ISSUE THREAD

**Issue by MerryOscar** [jovotech/jovo-framework-nodejs#180]
## I'm submitting a...
- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

When trying to display a Standard Card for Alexa by calling:

```javascript
this.alexaSkill().showImageCard('Title', 'Content', {
  smallImageUrl: 'https://www.jovo.tech/img/logo.png',
  largeImageUrl: 'https://www.jovo.tech/img/logo.png',
});
```
The card should be displayed as per the docs here - https://www.jovo.tech/docs/amazon-alexa/visual#standard-card

## Current Behavior

An error is thrown.

### Error log
```
TypeError: (intermediate value).setTitle(...).setText(...).setSmallImageUrl is not a function
    at AlexaResponse.addStandardCard (/Users/oscar/repos/test/node_modules/jovo-framework/lib/platforms/alexaSkill/alexaResponse.js:140:14)
    at AlexaSkill.showStandardCard (/Users/oscar/repos/test/node_modules/jovo-framework/lib/platforms/alexaSkill/alexaSkill.js:717:23)
    at AlexaSkill.showImageCard (/Users/oscar/repos/test/node_modules/jovo-framework/lib/platforms/alexaSkill/alexaSkill.js:701:21)
    at Object.renderWelcomeDisplay (/Users/oscar/repos/test/helpers/Display.js:24:24)
    at Jovo.Launch (/Users/oscar/repos/test/handlers/Launch.js:11:11)
    at Promise (/Users/oscar/repos/test/node_modules/jovo-framework/lib/handler.js:51:36)
    at new Promise (<anonymous>)
    at Handler.handle (/Users/oscar/repos/test/node_modules/jovo-framework/lib/handler.js:26:16)
    at loadUserDataOnRequest.then.then.then.then.then.then (/Users/oscar/repos/test/node_modules/jovo-framework/lib/jovo.js:186:43)
    at <anonymous>
```

## Your Environment
* Jovo Framework version used: 1.2.2

**Comment by MerryOscar** [comment]
This was caused by having the second `content` parameter as an empty string.
