### ISSUE TITLE
The parameter cannot be converted to a numeric value: NaN

### ISSUE THREAD

**Issue by QuentinDela** [jovotech/jovo-framework-nodejs#197]
## I'm submitting a...
- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Current Behavior
I am sometimes seeing this error in the logs which seems to be related with DynamoDB
"The parameter cannot be converted to a numeric value: NaN"
I was wondering if anyone has encountered this one.
I am not sure if this is coming from my code but it's emitted when the line this.ask() is run.

### Error log
```
Error on respond { ValidationException: The parameter cannot be converted to a numeric value: NaN
    at Request.extractError (/Users/Project/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/Project/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/Project/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/Project/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/Project/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/Project/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/Project/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/Project/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/Project/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/Project/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/Project/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/Project/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/Project/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/Project/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/Project/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/Project/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/Project/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/Project/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/Project/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/Users/Project/node_modules/aws-sdk/lib/event_listeners.js:286:13)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  message: 'The parameter cannot be converted to a numeric value: NaN',
  code: 'ValidationException',
  time: 2018-07-10T14:58:13.760Z,
  requestId: '5HA30MQIKM8FIG486JH1FVRK07VV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 17.462826587019265 }
```

## Your Environment
* Jovo Framework version used: 1.3.0
* Operating System: MacOS

**Comment by aswetlow** [comment]
Hasn't happened to me yet. What are your parameters for ask()?
